# Generated by Django 5.1 on 2024-08-27 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0004_profile_profile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="tweet_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
